# Generated by Django 6.0.1 on 2026-02-01 17:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='course',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='school',
        ),
        migrations.AddField(
            model_name='lead',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('Instagram', 'Instagram'), ('Tanish', 'Tanish orqali'), ('Telegram', 'Telegram'), ('Banner', 'Banner'), ("Maktab targ'iboti", "Maktab targ'iboti")], max_length=50),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('days', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='myapp.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='myapp.group'),
        ),
    ]
